service:
  name: sandbox-appsync

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs8.10

functions:
  graphql:
    handler: handler.graphqlHandler
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello


custom:
  appSync:
    name:  sandbox-api
    # apiId # only required for update-appsync
    authenticationType: AWS_IAM # API_KEY is also supported
    # region: # defaults to provider region
    # mappingTemplatesLocation: # defaults to mapping-templates
    mappingTemplates:
      - dataSource: Lambda
        type: Query
        field: meInfo
        request: "meInfo-request-mapping-template.vtl"
        response: "meInfo-response-mapping-template.vtl"
    # schema: # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AWS_LAMBDA
        name: Lambda
        description: 'Lambda DataSource'
        config:
          lambdaFunctionArn: !GetAtt GraphqlLambdaFunction.Arn
          serviceRoleArn: !GetAtt AppSyncServiceRole.Arn

resources:
  Resources:
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Lambda-${self:custom.appSync.serviceRole}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Lambda-${self:custom.appSync.serviceRole}-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                  Resource:
                    - "Fn::Join":
                      - ":"
                      - - "arn:aws:lambda"
                        - !Ref "AWS::Region"
                        - !Ref "AWS::AccountId"
                        - "function"
                        - "*"
